//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernApp4Me.WP8.Sample.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernApp4Me.WP8.Sample.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ajouter.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Élément de menu.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModernApp4Me Sample app.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Downloader.
        /// </summary>
        public static string BitmapDownloader {
            get {
                return ResourceManager.GetString("BitmapDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve the element: this screen cannot be displayed correctly. Sorry!.
        /// </summary>
        public static string BusinessObjectProblem {
            get {
                return ResourceManager.GetString("BusinessObjectProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change the city.
        /// </summary>
        public static string ChangeCity {
            get {
                return ResourceManager.GetString("ChangeCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device is not connected to the Internet.
        /// </summary>
        public static string ConnectivityProblem {
            get {
                return ResourceManager.GetString("ConnectivityProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Handler.
        /// </summary>
        public static string ExceptionHandler {
            get {
                return ResourceManager.GetString("ExceptionHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4MBusinessObjectUnavailableException.
        /// </summary>
        public static string ExceptionHandlerBusinessObjectException {
            get {
                return ResourceManager.GetString("ExceptionHandlerBusinessObjectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M4MConnectivityException.
        /// </summary>
        public static string ExceptionHandlerConnectivityException {
            get {
                return ResourceManager.GetString("ExceptionHandlerConnectivityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string ExceptionHandlerException {
            get {
                return ResourceManager.GetString("ExceptionHandlerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Exception.
        /// </summary>
        public static string ExceptionHandlerNavigationException {
            get {
                return ResourceManager.GetString("ExceptionHandlerNavigationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Profiler.
        /// </summary>
        public static string MemoryProfiler {
            get {
                return ResourceManager.GetString("MemoryProfiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Application Page.
        /// </summary>
        public static string PhoneApplicationPage {
            get {
                return ResourceManager.GetString("PhoneApplicationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to problem.
        /// </summary>
        public static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr-fr.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You discovered an issue into the application. Sorry !.
        /// </summary>
        public static string UnhandledProblem {
            get {
                return ResourceManager.GetString("UnhandledProblem", resourceCulture);
            }
        }
    }
}
